# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c4a34c56de6ebb3f9862b5981b8cfacd3cf154809b17174ee5a835ad12a41ad1f76993b575d7b3077470295328aeea6df0caaaca6efb6c01420f2fff1145dd

test:
  secret_key_base: 6d00a32465c9bab9630a5e3d1bdcb4dc86311b82114149fc6dab4e81e1ca3fba947393e26bf25908d9e6f8f64139e0b212be19d798795c4db230150fcc2dc580

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
